src/js/features/data/makeGetDataRequest.js
How to test:
Using the following config.json for Katsu (notice: it does not contain `extra_properties`), load the current main branch for bento_public. Check that you can reproduce the bug where no data is displayed.
Update your repo to this branch and check that everything is displayed correctly.
```json
{
"age": {
"type": "number",
"title": "Age",
"bin_size": 10,
"is_range": true,
"queryable": true,
"taper_left": 40,
"taper_right": 60,
"units": "years",
"minimum": 0,
"description": "Age at arrival"
},
"sex": {
"type": "string",
"enum": [
"Male",
"Female"
],
"title": "Sex",
"queryable": true,
"description": "Sex at birth"
},
"experiment_type": {
"type": "string",
"title": "Experiment Types",
"queriable": false,
"description": "Types of experiments performed on a sample"
}
}
```
=> Fix handle missing extra properties

src/js/components/Overview/OverviewDisplayData.js, src/js/components/Overview/OverviewSection.js, src/js/components/Overview/PublicOverview.js, src/js/components/Search/MakeQueryOption.js, src/js/components/Search/Search.js, src/js/components/Search/SearchFieldsStack.js, src/js/components/Search/SearchResults.js, src/js/components/SiteHeader.js, src/js/constants/configConstants.js, src/styles.css
- moved the search results to the top
- moved get data to the side as a floating button
- Bento public logo and the text next to it now do not overlap on zoom or small screen
- made overview charts response and responds well to screen size change
- made default chart load for a section to 3
=> Styling changes

.eslintrc.js, .gitignore, package.json, src/js/components/SiteHeader.tsx, src/js/constants/configConstants.ts, src/js/i18n.ts, src/js/index.tsx
**Issues**: After opening the site, we cant change the language until a route change is done
**Causes**: 
- In `src/js/index.tsx` the language url param was being set before i18n was initialized, causing it to be undefined (`/#/undefined`) until the next route change (when i18n.language is `en` or `fr`).
- Missing trailing `/` after language url param was preventing path replacement in `SiteHeader.changeLanguage`
**Other:**
- `SiteHeader.tsx` now accessing the i18n instance with the useTranslation hook
- added `www/` dir to .gitignore
=> fix: language change with url param

go.mod, package-lock.json, package.json, src/js/components/Search/MakeQueryOption.tsx, src/js/components/Search/Search.tsx, src/js/components/TabbedDashboard.tsx, src/js/features/search/query.store.ts, src/js/types/search.ts, src/js/utils/search.ts, tsconfig.json
- fix: error when selecting query option + bad selectors
- fix: include query parameters when returning to search page
- refact: move search URL-handling logic to a single location
=> fix: error when selecting query option + missing URL params in some cases

src/js/components/Search/Search.tsx, webpack.config.js
Chart click navigation was failing due to a faulty query parameters check (Search.tsx checkQueryParamsEqual).
Given the parameter "age", the function would spread each letter as its own parameter ("a", "g", "e"), causing `undefined === undefined` which evaluates to true always.
=> fix: chart click nav

src/js/components/Beacon/VariantsForm.tsx, src/js/types/beacon.ts
Remove blank "rules" array for assembly ID in variants search form (Redmine [#2010](https://206.12.92.46/issues/2010)):
- it's not needed, since there are no rules to apply (probably the form was originally built using a `map()` call, so it was put there for consistency with the other fields)
- having rules here breaks the form when the assembly ID field is empty (which can happen if more than one assembly is present): antd tries and fails to apply the rules to a blank field, even though there are no rules to apply. Since the way to search metadata only is to leave the variants form blank, blank fields need to be handled correctly.
=> beacon: remove form rules for assembly ID

src/js/features/beacon/beaconConfig.store.ts, src/js/features/beacon/beaconQuery.store.ts
Change beacon overview endpoint to `/overview` (Redmine [#1859](https://206.12.92.46/issues/1859))
=> beacon: use a different overview endpoint

src/js/features/beacon/beaconQuery.store.ts
Patch condition for parsing the summary statistics part of the beacon response. Previously if `info` existed in the response, then so did `info.bento`, but this is no longer the case. See Redmine [#2080](https://206.12.92.46/issues/2080?issue_count=20&issue_position=1&next_issue_id=2068).
=> patch condition for parsing beacon response

src/js/components/Search/SearchResultsPane.tsx
also reduces minimum height to what is necessary.
=> style: fix top margins on search overview chart headings

src/js/components/Overview/ChartCard.tsx
Card description now doesn't get cut off by the missing count. Done by reducing the rendering width for the description
=> Card description improvement

package-lock.json, src/js/components/Overview/Chart.tsx, src/js/constants/overviewConstants.ts, src/js/index.tsx, src/js/types/chartConfig.ts
- Now there is a distinction between bar charts and histogram supported by bento charts and katsu config (for labelling which is which)
- Bar charts are multi-colored while histograms are not
- There are new colors now
=> Added histograms

package-lock.json, package.json, src/js/components/Beacon/BeaconQueryUi.tsx, src/js/components/Search/MakeQueryOption.tsx, src/js/components/Search/Search.tsx, src/js/constants/configConstants.ts, src/js/features/config/config.store.ts, src/js/hooks.ts, src/js/index.tsx, src/js/types/configResponse.ts
Uses the public_rules endpoint to obtain censorship info.
=> fix: authorized beacon queries

src/js/components/BentoAppRouter.tsx, src/js/components/Overview/Chart.tsx, src/js/components/Overview/ChartCard.tsx, src/js/components/Overview/PublicOverview.tsx, src/js/features/data/data.store.ts, src/js/features/data/makeGetDataRequest.thunk.ts, src/js/features/search/query.store.ts, src/js/types/data.ts
This PR addresses the issue where clicking on non-searchable fields in the `bento_public` overview would trigger a search, leading to confusion as it returns results for the entire dataset.
There is now a clickable field on charts that is populated after the overview and query search fields are loaded and then there is a comparison. After this i done the charts are loaded to avoid unnecessary rerenders
=>  Disable Click-to-Search for Non-Searchable Fields in Overview

.gitignore
Remove dev headache: builds can crash during development, which produces a very large `core` file. This doesn't need to be tracked, and is large enough that it doesn't play nicely with VS Code's git UI.
=> gitignore core dump files

src/index.ejs
I think this was some experiment for use in a BQC19 website iframe attempt, but to my knowledge this isn't used anywhere (confirmed with David B).
=> chore: remove unused code for iframed Bento Public

src/js/components/Beacon/BeaconNetwork/NetworkBeacons.tsx, src/js/components/Beacon/BeaconNetwork/NetworkNodeDetails/NodeCountsDisplay.tsx, src/js/components/Beacon/BeaconNetwork/NetworkNodeDetails/NodeDetails.tsx, src/js/components/Search/SearchResultsPane.tsx
* Non-fixed-width network nodes
* Use Ant column/row system for nodes
* Removes some unnecessary CSS
* Fixes up titled search results display
* Adds logo alt text
=> style: beacon network styling

Dockerfile, dev.Dockerfile
Currently, containers created from `bento_public@edge` fail at start time due to missing `entrypoint.bash` file in the image.
=> fix: missing entrypoint in dockerfiles

src/js/components/Beacon/BeaconCommon/VariantsForm.tsx
now chromosome won't be disabled/"select an assembly"'d for beacon network, since there isn't a contig dropdown
=> chore: address confusing UX for network chromosome/assembly

src/js/components/BentoAppRouter.tsx, src/js/components/Scope/DatasetScopePicker.tsx, src/js/features/metadata/metadata.store.ts, src/js/utils/router.ts
by fixing, this means that datasets are now highlighted on selection in the scoping modal.
also refactors validProjectDataset to use a cleaner lookup into an object instead of an array.
=> fix: selector indicator for dataset scope selection

src/js/components/BentoAppRouter.tsx, src/js/features/config/hooks.ts, src/js/features/data/hooks.ts, src/js/features/data/makeGetDataRequest.thunk.ts
some issues with hook dependencies meant when a dataset without data was selected from a project card entry, for example, the overview would not refresh. this should fix the issue.
=> fix: config/overview sometimes not re-fetched on scope change

src/js/components/Beacon/BeaconCommon/Filters.tsx
Beacon was no longer pulling config values for max query params on loading, breaking the UI for filters.
=> Use config hook in beacon 

src/js/components/Beacon/BeaconCommon/BeaconQueryFormUi.tsx
Ignore any local scope in calls to beacons in beacon network. 
Although the "Beacon Network" tab is available only at instance-wide scope, it seems like instances with a single project and dataset can have scope present in redux, which broke some assumptions about scope in the beacon code.
=> Ignore scope in beacon network

src/js/components/Beacon/BeaconCommon/BeaconQueryFormUi.tsx, src/js/components/Beacon/BeaconCommon/Filter.tsx, src/js/components/Beacon/BeaconCommon/Filters.tsx, src/js/components/Beacon/BeaconNetwork/NetworkUi.tsx, src/js/components/Beacon/BeaconQueryUi.tsx, src/js/components/BentoAppRouter.tsx, src/js/features/beacon/beacon.store.ts, src/js/features/beacon/constants.ts, src/js/features/beacon/network.store.ts, src/js/features/beacon/utils.ts, src/js/types/beacon.ts
Previously, the beacon tab in bento public has used the same discovery config settings as the Search tab to set metadata search options. Since Bento 18, beacon now knows its own search options, so these can be pulled from the beacon endpoint `/filtering_terms` instead. 
- makes Beacon more self-contained and closer to its intended use: 
- it's now beacon's job to call katsu to figure out what the search options are, rather than leaving this to the web client
- leaves open the possibility of filters that apply to other services (eg Takuan)
- ideally the beacon UI should only need to communicate with beacon
- leaves open the possibility of working with non-Bento beacons
... and in general relying more on beacon `/filtering_terms` instead of direct calls to katsu will simplify the operation …
=> Pull search options from beacon 

src/js/features/beacon/beacon.store.ts, src/js/types/beacon.ts
Deprecate old beacon overview response format. (Redmine #2541)
Beacon currently sends old and new formats together, so this is non-breaking.
=> deprecate old beacon overview response format

src/js/components/Beacon/BeaconSearchResults.tsx, src/js/components/Search/SearchResults.tsx, src/js/components/Search/SearchResultsCounts.tsx, src/js/components/Search/SearchResultsPane.tsx, src/js/features/beacon/utils.ts, src/js/hooks/censorship.ts
Handle uncensored zero results from beacon: show "0" instead of "Insufficient data available". (Redmine #2360)
Related changes:
- remove stale beacon search overview values when no results (bug was masked by censored count handling)
- fix threshold handling (threshold is inclusive)
- remove prop drilling for `uncensoredCounts` value
... I'd hoped to eliminate one of the two bools responsible for showing zero or "insufficient data" (`hasInsufficientData` and `uncensoredCounts`) but the first one is a legacy of katsu's response for a censored zero response, which is just:
`{message: "Insufficient data available."}`
with no actual zero to count.
=> Beacon uncensored zeros

src/js/components/Overview/OverviewChartDashboard.tsx, src/js/components/Overview/OverviewDatasets.tsx, src/js/components/Overview/OverviewSection.tsx, src/js/components/Overview/Util/OverviewCollapsibleSection.tsx, src/styles.css
goal: allow users to reduce the possibly-overwhelming amount of info shown on the overview page without having to fully hide charts/sections via the chart manager.
also (newly) allows collapsing the overview datasets view.
=> feat(overview): collapsible overview sections

src/js/components/ClinPhen/PhenopacketDisplay/BiosampleView.tsx, src/js/components/ClinPhen/PhenopacketDisplay/DiseasesView.tsx, src/js/components/ClinPhen/PhenopacketDisplay/InterpretationsView.tsx, src/js/components/ClinPhen/PhenopacketDisplay/MeasurementsView.tsx, src/js/components/ClinPhen/PhenopacketDisplay/MedicalActionsView.tsx, src/js/components/ClinPhen/PhenopacketDisplay/OntologiesView.tsx, src/js/components/ClinPhen/PhenopacketDisplay/PhenotypicFeaturesView.tsx, src/js/components/ClinPhen/PhenopacketDisplay/SubjectView.tsx, src/js/components/ClinPhen/PhenopacketView.tsx, src/js/components/Scope/ScopedTitle.tsx, src/js/components/Util/ClinPhen/Excluded.tsx, src/js/components/Util/ClinPhen/Procedure.tsx, src/js/components/Util/CustomTable.tsx, src/js/features/ui/hooks.ts, src/js/features/ui/ui.store.ts, src/js/hooks/navigation.tsx, src/js/hooks/usePhenopacketTabs.tsx, src/js/store.ts, src/js/types/clinPhen/phenopacket.ts, src/js/types/util.ts, src/js/utils/tables.ts, src/public/locales/en/default_translation_en.json, src/public/locales/fr/default_translation_fr.json, src/styles.css
* More compact tables/descriptions
* Add missing `gender` property to subject view
* Higher information density in medical actions/interpretations tables by showing some nested properties in the main table
* "Nice" title for phenopacket vs. ID (subject ID or biosample ID list)
* Some translation fixes
* Typing fixes
=> More improvements for phenopacket display

src/js/features/beacon/network.store.ts, src/js/types/beacon.ts, src/js/types/beaconNetwork.ts
Requires [Beacon pr #138](https://github.com/bento-platform/bento_beacon/pull/138).
Deprecate the use of katsu-format querySections in beacon network, use beacon filtering terms only.
=> use beacon-standard filters in beacon network

src/js/components/BentoAppRouter.tsx, src/js/features/config/hooks.ts
Fixed the following bug: bento public behaves incorrectly when there are multiple projects. In particular it erroneously checks the top-level `/public_rules`  in situations where it should check `/public_rules/<project_id>` instead.
=> Fixed rule call sequence
