- src/js/action.js
- src/js/components/QueryParameter.js
- src/main.go
- crude 'range' type implemention
> v0.1.1 candidate

- package.json
- src/js/components/QueryParameter.js
> v0.1.2 candidate

- Makefile
- docker-compose.dev.yaml
- docker-compose.yaml
> v0.1.3 candidate

- etc/example.client.env
- src/js/action.js
- src/js/components/QueryParameter.js
- src/js/constants.js
- src/js/reducer.js
- src/js/utils.js
> v0.1.4 candidate

- .gitignore
- Dockerfile
- README.md
- buildandrun.sh
- etc/example.katsu.config.json
- src/js/action.js
- src/js/components/QueryParameter.js
- src/main.go
> v0.1.5 candidate

- src/js/components/BentoBarChart.js
Bar chart handling for "missing" category:
- separate colouring
- only show if non-zero
> handling for "missing" in bar charts

- src/js/components/BentoBarChart.js
Bar Charts:
- tone down bar colours 
- fix tick label cropping
> improved bar chart colour & tick labels

- src/js/action.js
- src/js/components/BentoBarChart.js
- src/js/components/BentoPie.js
- src/js/components/Header.js
- src/js/components/PublicOverview.js
- src/js/components/Search.js
- src/js/components/SearchResults.js
- src/js/components/TabbedDashboard.js
- src/js/constants.js
- src/js/index.js
- src/js/reducer.js
- src/js/store.js
- src/styles.css
- add tabbed navigation
- first pass at results formatting
- styling updates
- expose redux devtools
> Tabbed navigation and results formatting

- src/js/features/data/makeGetDataRequest.js
Fix for missing extra_properties in overview.
> patch for missing overview extra_properties

- src/index.ejs
- Removed bootstrap css import 
- Added a template title
> removed bootstrap import

- package.json
- src/js/components/Search/SearchResults.js
- src/js/features/data/makeGetDataRequest.js
- src/js/features/search/makeGetKatsuPublic.js
- src/js/features/search/query.js
- src/js/utils/chart.js
- Created a utility function out of serializing charts
- Added biosample and experiment counts and charts to the search result
> Search chart resp

- src/js/components/Overview/MakeChartCard.js
- src/js/components/Overview/OverviewDisplayData.js
- src/js/components/SiteHeader.js
- src/js/constants/overviewConstants.js
- src/styles.css
- Added tooltip icon to chart card
- curved card corners on overview and provenance
- resolved header where portal  button went out of bounds
- resolved issue where getdata button teleported and came back
> Styling changes

- src/js/components/Overview/charts/BentoBarChart.js
- src/js/components/Overview/charts/BentoPie.js
- pie charts now would not have missing fields 
- removed bug from bar charts where french version contained missing field
> fixed missing fields

- package.json
- src/js/components/Overview/Drawer/ManageChartsDrawer.js
- src/js/components/Overview/PublicOverview.js
- src/js/components/Overview/charts/BentoPie.js
- src/js/components/Provenance/DatasetProvenance.js
- src/js/components/Provenance/ProvenanceTab.js
- src/js/components/Search/SearchResults.js
- src/js/components/SiteHeader.js
- src/js/components/TabbedDashboard.js
- src/js/index.js
- src/public/locales/en/default_translation_en.json
- src/styles.css
- fixed translation issue on tooltip
- fixed translation issue on insufficient data message
- header buttons rounded
- Upgraded to antdv5
- optimized tabpane rendering to be more scalable
> Fix translation issues, tweak styling, and upgrade to Ant Design 5

- Dockerfile
- temporarily use build-dev in dockerfile to avoid axios error
> v0.7.1 rc-1

- package-lock.json
- package.json
- src/js/components/Overview/PublicOverview.js
- Everything should be centred correctly irrelevant of amount of text for about
> Fixed bug: About section didnt have maxWidth css prop

- package-lock.json
- package.json
- src/js/components/Overview/charts/BentoBarChart.js
* Show more labels for bar charts with few categories
* Increase X axis label distance to avoid some overlaps
> Chart improvements

- src/js/components/SiteFooter.js
branding: increase Bento logo size in footer
> feature 1406

- src/js/components/Overview/Counts.js
- src/js/components/Overview/PublicOverview.js
- src/js/components/Overview/charts/BentoPie.js
- src/js/components/Overview/charts/Chart.js
- src/js/components/Search/Search.js
- src/js/components/Search/SearchResults.js
- src/js/components/TabbedDashboard.js
- src/js/features/data/data.js
- src/js/features/data/makeGetDataRequest.js
- src/js/features/search/makeGetKatsuPublic.js
- Increased chart render area
- enabled sorting on all charts
- Added all counts: individuals, biosamples, experiments
> Removed chart overlap, chart data is sorted, added counts

- package-lock.json
- package.json
- src/js/components/Search/Search.js
- src/js/components/Search/SearchResults.js
- src/public/locales/en/default_translation_en.json
- src/public/locales/fr/default_translation_fr.json
Search page patches
- added 'back to top' button
- added 'loading' status to results card
- patched card height jumpiness
> v0.9.1 rc-1

- package.json
- run.dev.bash
- webpack.config.js
Fix dev container to reload webpack changes
> fix: webpack in dev container

- package-lock.json
- package.json
> fix(bento-charts): version bump to fix pie charts labels position

- src/js/components/Search/SearchResults.tsx
- src/js/features/search/query.store.ts
- src/js/types/search.ts
- Removed unnecessary is valid variable
- The typescript interface for search response was incorrect causing issues for search not being loaded correctly which is now resolved
> Fixed rendering of charts in search response

- .eslintrc.js
- .github/workflows/lint.yml
- package.json
- src/js/components/Search/MakeQueryOption.tsx
- src/js/components/Search/SearchResults.tsx
- src/js/components/Search/SelectOption.tsx
- src/js/features/search/makeGetSearchFields.thunk.ts
- src/js/types/search.ts
Also formats the whole project according to Prettier
> Add new lint rule & run Prettier check in CI

- src/public/about.html
- src/public/en_about.html
- src/public/fr_about.html
Remove static about HTML files from `src/public/`. These files are to be provided through docker mounts.
See bento PR for this patch [here](https://github.com/bento-platform/bento/pull/136).
> patch: remove static about files

- package-lock.json
- package.json
- src/js/components/Overview/Chart.tsx
- src/js/components/Overview/MakeChartCard.tsx
clicking a chart section to charts now redirects you to corresponding search
> Added onClick functionality to charts

- src/js/components/Provenance/DatasetProvenance.tsx
- src/js/components/Provenance/DownloadDats.tsx
- src/js/components/Provenance/Tables/AcknowledgesTable.tsx
- src/js/components/Provenance/Tables/BaseProvenanceTable.tsx
- src/js/components/Provenance/Tables/CreatedByTable.tsx
- src/js/components/Provenance/Tables/DistributionsTable.tsx
- src/js/components/Provenance/Tables/ExtraPropertiesTable.tsx
- src/js/components/Provenance/Tables/IsAboutTable.tsx
- src/js/components/Provenance/Tables/PublicationsTable.tsx
- src/js/components/Provenance/Tables/SpatialCoverageTable.tsx
* make all tables the same size & give them borders
* render taxonomies in italics in the "Is about" section
> chore: update provenance styling + minor refactor

- src/js/features/beacon/beaconQuery.store.ts
- src/js/types/beacon.ts
corrected beacon response param
> beacon "count" -> "numTotalResults"

- src/js/components/SiteFooter.tsx
> chore: update copyright to 2024

- src/js/components/Overview/Drawer/ManageChartsDrawer.tsx
- src/js/features/data/data.store.ts
- src/js/features/data/makeGetDataRequest.thunk.ts
Added button the manage charts drawer to reset the layout to the original, including width other than sequence & isDisplayed.
> feat: reset button for chart layout

- src/js/components/BentoAppRouter.tsx
- src/js/components/SiteSider.tsx
- src/js/types/routes.ts
- src/js/utils/router.ts
Enabled the possibility of rendering beacon conditionally
> conditional-beacon

- package-lock.json
- package.json
This should address the 400 error spam for refreshing token attempts when no refresh token was present.
> chore(deps): update auth-js and other dependencies

- src/js/components/Beacon/BeaconCommon/BeaconQueryFormUi.tsx
- src/js/components/Beacon/BeaconNetwork/NetworkBeacons.tsx
- src/js/components/Beacon/BeaconNetwork/NetworkNodeDetails/NodeCountsDisplay.tsx
- src/js/components/Beacon/BeaconNetwork/NetworkNodeDetails/NodeDetails.tsx
- src/js/components/Beacon/BeaconNetwork/NetworkSearchResults.tsx
- src/js/components/Beacon/BeaconSearchResults.tsx
- src/js/components/Search/SearchResults.tsx
- src/js/components/Search/SearchResultsCounts.tsx
- src/js/components/Search/SearchResultsPane.tsx
- src/js/constants/searchConstants.ts
- src/js/features/beacon/beaconConfig.store.ts
- src/js/features/beacon/beaconQuery.store.ts
- src/js/features/beacon/networkConfig.store.ts
- src/js/features/beacon/networkQuery.store.ts
- src/js/features/search/query.store.ts
- src/js/types/beacon.ts
- src/js/types/beaconNetwork.ts
- src/js/types/data.ts
- src/js/types/search.ts
- src/js/utils/beaconApiError.ts
also some misc. beacon network tweaks
> refact: factor out common types for discovery results + new types

- src/js/components/Overview/Chart.tsx
- src/js/components/Overview/ChartCard.tsx
- src/js/components/Overview/OverviewDisplayData.tsx
also replaces a useDispatch elsewhere with useAppDispatch
> refact(overview): use relative nav paths + helper fn

- src/js/components/Overview/Chart.tsx
- src/js/components/Overview/ChartCard.tsx
- src/js/components/Overview/OverviewDisplayData.tsx
Reverts bento-platform/bento_public#213
> Revert "refact(overview): use relative nav paths + helper fn"

- src/js/components/Overview/PublicOverview.tsx
This makes the button's meaning more explicitly visualised.
> Added New Chart Manager Drawer

- src/js/components/Overview/PublicOverview.tsx
- src/js/features/content/content.store.ts
- src/js/types/requests.ts
> refact: rewrite content slice with request state

- package-lock.json
- package.json
- src/js/components/Overview/Chart.tsx
fixes: https://redmine.c3g-app.sd4h.ca/issues/2379
issue: On translated bars/slice on chart on click search wasn't working correctly as it used to redirect to the french label for the search but the backend only supports english keys, now the requests are translation agnostic.
> fix: chart clicking in French

- src/js/components/BentoAppRouter.tsx
Fixes https://redmine.c3g-app.sd4h.ca/issues/2385
> fix: double loading/counts flicker for overview

- package.json
- webpack.config.js
my dist folder was bloating gradually because of webpack dev server, this should fix that issue.
to test, make sure old JS files are deleted in dev mode across restarts.
> chore: configure webpack to clean up dist/

- package-lock.json
- package.json
- src/js/components/Overview/Counts.tsx
- src/js/components/Search/SearchResultsCounts.tsx
- src/js/components/Util/CountsTitleWithHelp.tsx
- src/js/types/entities.ts
https://redmine.c3g-app.sd4h.ca/issues/2412
> feat: search count help text

- create_config_prod.js
- src/js/components/SiteHeader.tsx
- src/js/config.ts
- src/public/config.js
- webpack.config.js
see also https://github.com/bento-platform/bento/pull/302/files
> feat: add branding options for showing/hiding header links

- .eslintrc.js
- src/js/components/Beacon/BeaconCommon/BeaconQueryFormUi.tsx
- src/js/components/Util/CustomEmpty.tsx
if hook dependencies are truly optional, an exception comment disabling eslint for the line can be added
> lint: enforce hook dependencies + CustomEmpty -> tsx
